FROM node:18.16-bullseye-slim as builder-node
WORKDIR /work
COPY client/package.json package.json
COPY client/package-lock.json package-lock.json
RUN npm config set registry https://registry.npm.taobao.org && npm install
COPY client .
RUN npm run build
CMD ["npm", "start"]